tls:
  keystore:    
    keyPassword: "![KCyFyi9rvi0/bS4Jqd1XG9SoyjmF9Kcx]" 
    password: "![KCyFyi9rvi0/bS4Jqd1XG9SoyjmF9Kcx]"
    
covid19CaseDataDatabase:    
  password: "![sxHTyHjyv9LdyqhGzyv15Q==]"